"""create company

Revision ID: 36746894c89e
Revises: 11abaf7a8435
Create Date: 2025-08-09 10:11:40.158603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36746894c89e'
down_revision: Union[str, Sequence[str], None] = '11abaf7a8435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('business_entity', sa.String(), nullable=True),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('contract_issue_date', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('funeral_home', 'logistics_services', 'burial_care_contractor', name='companytype'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='companystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_short_name'), 'companies', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_short_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
